{{- if .Values.yandexLoadBalancer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "x5-test.fullname" . }}-nginx-cert
  labels:
    {{- include "x5-test.nginx-cert.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "x5-test.nginx-cert.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "x5-test.name" . }}-nginx-cert
        app.kubernetes.io/instance: {{ .Release.Name }}-nginx-cert
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx-cert
          image: "{{ .Values.yandexLoadBalancer.nginxCert.image.repository }}:{{ .Values.yandexLoadBalancer.nginxCert.image.tag | default 1.0 }}"
          env:
          {{- range $key, $val := .Values.yandexLoadBalancer.nginxCert.env }}
          - name: {{$key}}
            value: {{ $val | quote }}
          {{- end }}
          - name: PROXY_PASS_HOST
            value: {{ include "x5-test.fullname" . }}
          - name: PROXY_PASS_PORT
            value: "80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.yandexLoadBalancer.nginxCert.resources | nindent 12 }}
      {{- with .Values.yandexLoadBalancer.nginxCert.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.yandexLoadBalancer.nginxCert.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.yandexLoadBalancer.nginxCert.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
